# clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-deployer
rules:
  - apiGroups: ["", "apps", "networking.k8s.io"]
    resources: ["deployments", "services", "pods", "secrets", "persistentvolumeclaims", "ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
