# clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-deployer-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default  # Or your Tekton namespace if not 'default'
roleRef:
  kind: ClusterRole
  name: tekton-deployer
  apiGroup: rbac.authorization.k8s.io
